### ISSUE TITLE
Where is the kc-cloudtrust-module parent pom?

### ISSUE THREAD

**Issue by xgp** [cloudtrust/event-emitter#29]
I get a compilation error because the kc-cloudtrust-module parent pom isn't in maven central. Where is the code for that?

**Comment by xgp** [comment]
NVM. Found it: https://github.com/cloudtrust/cloudtrust-parent

**Comment by vloup** [comment]
Hello,

Good question, you can find that module in our generic parent repository at https://github.com/cloudtrust/cloudtrust-parent
Just checkout the code and run `mvn install`.
We've not had yet time to consider adding it to maven central.

The pom architecture is made such that you should not need more hidden repositories than cloudtrust-parent to build the module. If cloudtrust-parent successfully installs, you're good to go.
Still, I strongly suggest that you build a keycloak since the test dependencies neither are published on maven central.

I've updated this morning the release for keycloak 8.x.
